### PR TITLE
upgrade sqlite3 to version 3.8.8.2

### PR DESCRIPTION
**Pull request by darealshinji**
I'm using the amalgamation version because the other version didn't build.

### CODE REVIEW

**Comment by johnmurrayvi** [comment]
The current in-tree sqlite is patched a bit IIRC.
https://github.com/nightingale-media-player/nightingale-deps/commit/0a0fb993aaf892b024648c1037914f326b3e70ae
https://github.com/nightingale-media-player/nightingale-deps/commit/7e2162c765dc4e1cda548a5a94078e07c02a7b76

Can't remember what else, if anything, there was. But, I think the mediacore relies on the SQLITE_CORRUPT return values for some things

**Comment by darealshinji** [comment]
I'v been using a build with this version of sqlite for a few days and I haven't had any problems yet (Ubuntu 14.04 64 bit).

**Comment by ilikenwf** [comment]
Have you tried 3.8.11? When using the system sqlite per https://github.com/nightingale-media-player/nightingale-hacking/commit/6e116b4fe6771c34559802fdea71be5a1d2739c9 , I can't start ngale because of something db related. Something in how it is built seems to be at fault?

**Comment by darealshinji** [comment]
Yeah, somehow it doesn't work with the system's version. I've tested version 3.8.11.1 and it works. I'm going to update it.

**Pull request closed without merging**
