### PR TITLE
update config programs with current version taken from http://git.savann...

### PR DESCRIPTION
**Pull request by darealshinji**
...ah.gnu.org/cgit/config.git/tree/

Some of these files were extremely outdated, so why not?

### CODE REVIEW

**Comment by mook** [comment]
Would this present any issues in the future trying to update the relevant
source packages? Merge conflicts and that sort of thing.

**Comment by darealshinji** [comment]
I don't think so.

**Comment by darealshinji** [comment]
So... should I merge the pull request?

**Comment by johnmurrayvi** [comment]
Let me try building on win first to see if it complains. Win is very picky about things :(

**Comment by johnmurrayvi** [comment]
It seems to be building fine on Win. If it does cause any issues, we can revert it. Hopefully we'll be using the xul-9.0.1 branch soon enough and the newer package versions will have updated some of these.

**Pull request merged**
